name: Generate Snek Animation

on:
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snek.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: snek.svg?palette=github-dark

      - name: Push snek.svg
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Upload snek.svg'
          git push
